name: Basic Tests
on: pull_request
jobs:
  pytest:
    name: Run pytest tests
    runs-on: ubuntu-latest
    steps:
      - name: Common Setup
        uses: ./.github/actions/setup.yml
      - name: Install other dependencies
        run: sudo apt install -y jq gojq
      - name: Test
        run: uv run --frozen pytest
  isort:
    name: Run pytest tests
    runs-on: ubuntu-latest
    steps:
      - name: Common Setup
        uses: ./.github/actions/setup.yml
      - name: Run isort
        run: uv run --frozen isort
